-- ============================================================================
-- TSYS_BITACORA / TSYS_BITACORA_DETALLE : historial/auditoría cross-módulo
-- Owner: ABREGONZA
-- Spec : backend/docs/superpowers/specs/2026-07-31-historial-auditoria-design.md
-- NO se ejecuta automaticamente. Correr manualmente:
--   docker compose exec backend python apps/historial/sql/_run_001.py
--
-- NOTA (desviación del plan original): el plan pedía BITACORA_ID/DETALLE_ID
-- como NUMBER GENERATED ALWAYS AS IDENTITY, pero esta instancia es Oracle
-- 11g y esa sintaxis requiere 12c+ (falla con ORA-02000). Se usa el patrón
-- ya establecido en este mismo repo para PKs numéricos autogenerados en
-- 11g: secuencia + trigger BEFORE INSERT (ver
-- backend/apps/lic/sql/001_create_tlic.sql). Los tipos/índices/columnas
-- restantes son exactamente los del plan.
-- ============================================================================

CREATE TABLE ABREGONZA.TSYS_BITACORA (
    BITACORA_ID     NUMBER PRIMARY KEY,
    FECHA           DATE          DEFAULT SYSDATE NOT NULL,
    USUARIO         VARCHAR2(30)  NOT NULL,
    NO_CIA          VARCHAR2(2)   NOT NULL,
    PUNTO           VARCHAR2(2),
    MODULO          VARCHAR2(10)  NOT NULL,
    TIPO_DOCUMENTO  VARCHAR2(10)  NOT NULL,
    NO_DOCUMENTO    VARCHAR2(15)  NOT NULL,
    ACCION          VARCHAR2(15)  NOT NULL,
    MOTIVO          VARCHAR2(500),
    DESCRIPCION     VARCHAR2(500) NOT NULL,
    CONSTRAINT CK_TSYS_BITACORA_ACCION CHECK (
        ACCION IN ('CREAR','EDITAR','ANULAR','REVERSAR')
    )
);
/

CREATE SEQUENCE ABREGONZA.SEQ_TSYS_BITACORA;
/

CREATE OR REPLACE TRIGGER ABREGONZA.TRG_TSYS_BITACORA_ID
BEFORE INSERT ON ABREGONZA.TSYS_BITACORA
FOR EACH ROW
WHEN (NEW.BITACORA_ID IS NULL)
BEGIN
    :NEW.BITACORA_ID := ABREGONZA.SEQ_TSYS_BITACORA.NEXTVAL;
END;
/

CREATE INDEX IX_TSYS_BITACORA_DOC   ON ABREGONZA.TSYS_BITACORA (NO_CIA, MODULO, TIPO_DOCUMENTO, NO_DOCUMENTO, FECHA DESC);
/

CREATE INDEX IX_TSYS_BITACORA_USR   ON ABREGONZA.TSYS_BITACORA (USUARIO, FECHA DESC);
/

CREATE INDEX IX_TSYS_BITACORA_FECHA ON ABREGONZA.TSYS_BITACORA (FECHA DESC);
/

CREATE TABLE ABREGONZA.TSYS_BITACORA_DETALLE (
    DETALLE_ID      NUMBER PRIMARY KEY,
    BITACORA_ID     NUMBER        NOT NULL,
    CAMPO           VARCHAR2(60)  NOT NULL,
    ETIQUETA        VARCHAR2(60)  NOT NULL,
    VALOR_ANTERIOR  VARCHAR2(1000),
    VALOR_NUEVO     VARCHAR2(1000),
    CONSTRAINT FK_TSYS_BITACORA_DETALLE
        FOREIGN KEY (BITACORA_ID) REFERENCES ABREGONZA.TSYS_BITACORA(BITACORA_ID)
        ON DELETE CASCADE
);
/

CREATE SEQUENCE ABREGONZA.SEQ_TSYS_BITACORA_DET;
/

CREATE OR REPLACE TRIGGER ABREGONZA.TRG_TSYS_BITACORA_DET_ID
BEFORE INSERT ON ABREGONZA.TSYS_BITACORA_DETALLE
FOR EACH ROW
WHEN (NEW.DETALLE_ID IS NULL)
BEGIN
    :NEW.DETALLE_ID := ABREGONZA.SEQ_TSYS_BITACORA_DET.NEXTVAL;
END;
/

CREATE INDEX IX_TSYS_BITACORA_DET_HDR ON ABREGONZA.TSYS_BITACORA_DETALLE (BITACORA_ID);
/

GRANT SELECT, INSERT, UPDATE, DELETE ON ABREGONZA.TSYS_BITACORA TO JCABREU;
/

GRANT SELECT, INSERT, UPDATE, DELETE ON ABREGONZA.TSYS_BITACORA_DETALLE TO JCABREU;
/

GRANT SELECT ON ABREGONZA.SEQ_TSYS_BITACORA TO JCABREU;
/

GRANT SELECT ON ABREGONZA.SEQ_TSYS_BITACORA_DET TO JCABREU;
/

CREATE OR REPLACE SYNONYM JCABREU.TSYS_BITACORA         FOR ABREGONZA.TSYS_BITACORA;
/

CREATE OR REPLACE SYNONYM JCABREU.TSYS_BITACORA_DETALLE FOR ABREGONZA.TSYS_BITACORA_DETALLE;
/

CREATE OR REPLACE SYNONYM JCABREU.SEQ_TSYS_BITACORA      FOR ABREGONZA.SEQ_TSYS_BITACORA;
/

CREATE OR REPLACE SYNONYM JCABREU.SEQ_TSYS_BITACORA_DET  FOR ABREGONZA.SEQ_TSYS_BITACORA_DET;
/

COMMIT;
EXIT;
