-- Facturación Electrónica (e-CF) — Fase 1
-- Ejecutado 2026-07-07 vía conexión backend (usuario JCABREU, privilegios ANY TABLE).
-- El backend conecta como JCABREU, por lo que no se requieren grants adicionales.

-- Configuración FE por empresa
CREATE TABLE FAT.TFE_CONFIG (
  NO_CIA            VARCHAR2(2)   NOT NULL,
  AMBIENTE          VARCHAR2(10)  DEFAULT 'testecf' NOT NULL, -- testecf|certecf|ecf
  RNC_EMISOR        VARCHAR2(11)  NOT NULL,
  RAZON_SOCIAL      VARCHAR2(150) NOT NULL,
  NOMBRE_COMERCIAL  VARCHAR2(150),
  DIRECCION_EMISOR  VARCHAR2(250),
  MUNICIPIO         VARCHAR2(6),
  PROVINCIA         VARCHAR2(6),
  CERTIFICADO_P12   BLOB,
  CERT_PASSWORD_ENC VARCHAR2(500),
  CERT_SUBJECT      VARCHAR2(250),
  CERT_VENCE        DATE,
  ESTADO_CERT       VARCHAR2(15) DEFAULT 'NO_INICIADO',
  ACTIVO            VARCHAR2(1)  DEFAULT 'N',
  FECHA_ACTUALIZA   DATE         DEFAULT SYSDATE,
  CONSTRAINT PK_TFE_CONFIG PRIMARY KEY (NO_CIA)
);

-- Secuencias e-NCF autorizadas (espejo electrónico de TCNT_NCF)
CREATE TABLE FAT.TFE_SECUENCIA (
  NO_CIA          VARCHAR2(2)  NOT NULL,
  TIPO_ECF        VARCHAR2(2)  NOT NULL,
  SECUENCIA_DESDE NUMBER(10)   NOT NULL,
  SECUENCIA_HASTA NUMBER(10)   NOT NULL,
  PROX_SECUENCIA  NUMBER(10)   NOT NULL,
  FECHA_VENCE     DATE         NOT NULL,
  ACTIVA          VARCHAR2(1)  DEFAULT 'S',
  CONSTRAINT PK_TFE_SECUENCIA PRIMARY KEY (NO_CIA, TIPO_ECF, SECUENCIA_DESDE)
);

-- Bitácora/cola de documentos electrónicos emitidos
CREATE TABLE FAT.TFE_DOCUMENTO (
  NO_CIA           VARCHAR2(2)  NOT NULL,
  E_NCF            VARCHAR2(13) NOT NULL,
  TIPO_ECF         VARCHAR2(2)  NOT NULL,
  PUNTO            VARCHAR2(2),
  TIPO_DOCU        VARCHAR2(2),
  NO_DOCU          VARCHAR2(7),
  RNC_COMPRADOR    VARCHAR2(11),
  MONTO_TOTAL      NUMBER(14,2),
  ESTADO           VARCHAR2(22) DEFAULT 'PENDIENTE',
  TRACK_ID         VARCHAR2(64),
  CODIGO_SEGURIDAD VARCHAR2(6),
  FECHA_FIRMA      DATE,
  XML_FIRMADO      CLOB,
  RESPUESTA_DGII   CLOB,
  INTENTOS         NUMBER(3) DEFAULT 0,
  FECHA_CREA       DATE DEFAULT SYSDATE,
  FECHA_ACTUALIZA  DATE,
  CONSTRAINT PK_TFE_DOCUMENTO PRIMARY KEY (NO_CIA, E_NCF)
);

-- Cache de tokens DGII (~1h por cía+ambiente)
CREATE TABLE FAT.TFE_TOKEN (
  NO_CIA   VARCHAR2(2)    NOT NULL,
  AMBIENTE VARCHAR2(10)   NOT NULL,
  TOKEN    VARCHAR2(2500) NOT NULL,
  EXPIRA   DATE           NOT NULL,
  CONSTRAINT PK_TFE_TOKEN PRIMARY KEY (NO_CIA, AMBIENTE)
);
