-- Ejecutar manualmente contra Oracle (mismo patrón que backend/docs/sql/2026-07-07-fe-tablas.sql)
-- Schema: FAT (mismo schema compartido que usan otros módulos nuevos, ej. TFE_*)
-- Oracle 11g: PK autogenerado via secuencia+trigger, no soporta IDENTITY (12c+)

CREATE TABLE FAT.TLIC_CREDENCIAL (
    ID               NUMBER PRIMARY KEY,
    NO_CIA           VARCHAR2(2) NOT NULL,
    USUARIO_PORTAL   VARCHAR2(100) NOT NULL,
    PASSWORD_CIFRADO VARCHAR2(500) NOT NULL,
    ESTADO           VARCHAR2(20) DEFAULT 'activo' NOT NULL,
    ULTIMO_LOGIN_OK  TIMESTAMP,
    ULTIMO_ERROR     VARCHAR2(1000),
    ACTUALIZADO_EN   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_TLIC_CREDENCIAL_CIA UNIQUE (NO_CIA),
    CONSTRAINT CK_TLIC_CREDENCIAL_ESTADO CHECK (ESTADO IN ('activo', 'error_login'))
);
/

CREATE SEQUENCE FAT.SEQ_TLIC_CREDENCIAL;
/

CREATE OR REPLACE TRIGGER FAT.TRG_TLIC_CREDENCIAL_ID
BEFORE INSERT ON FAT.TLIC_CREDENCIAL
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    :NEW.ID := FAT.SEQ_TLIC_CREDENCIAL.NEXTVAL;
END;
/

CREATE TABLE FAT.TLIC_RUBRO_PDF (
    ID                NUMBER PRIMARY KEY,
    NO_CIA            VARCHAR2(2) NOT NULL,
    NOMBRE_ARCHIVO    VARCHAR2(300) NOT NULL,
    RUTA_ARCHIVO      VARCHAR2(500) NOT NULL,
    ESTADO_EXTRACCION VARCHAR2(20) DEFAULT 'pendiente' NOT NULL,
    MENSAJE_ERROR     VARCHAR2(1000),
    CREADO_EN         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_TLIC_RUBRO_PDF_ESTADO_EXT CHECK (ESTADO_EXTRACCION IN ('pendiente', 'hecho', 'error'))
);
/

CREATE SEQUENCE FAT.SEQ_TLIC_RUBRO_PDF;
/

CREATE OR REPLACE TRIGGER FAT.TRG_TLIC_RUBRO_PDF_ID
BEFORE INSERT ON FAT.TLIC_RUBRO_PDF
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    :NEW.ID := FAT.SEQ_TLIC_RUBRO_PDF.NEXTVAL;
END;
/

CREATE TABLE FAT.TLIC_RUBRO (
    ID           NUMBER PRIMARY KEY,
    RUBRO_PDF_ID NUMBER NOT NULL,
    CODIGO       VARCHAR2(50),
    DESCRIPCION  VARCHAR2(500) NOT NULL,
    CONSTRAINT FK_TLIC_RUBRO_PDFID FOREIGN KEY (RUBRO_PDF_ID) REFERENCES FAT.TLIC_RUBRO_PDF(ID)
        ON DELETE CASCADE
);
/

CREATE INDEX FAT.IX_TLIC_RUBRO_PDF ON FAT.TLIC_RUBRO (RUBRO_PDF_ID);
/

CREATE SEQUENCE FAT.SEQ_TLIC_RUBRO;
/

CREATE OR REPLACE TRIGGER FAT.TRG_TLIC_RUBRO_ID
BEFORE INSERT ON FAT.TLIC_RUBRO
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    :NEW.ID := FAT.SEQ_TLIC_RUBRO.NEXTVAL;
END;
/

CREATE TABLE FAT.TLIC_OPORTUNIDAD (
    ID                   NUMBER PRIMARY KEY,
    NO_CIA               VARCHAR2(2) NOT NULL,
    REFERENCIA           VARCHAR2(60) NOT NULL,
    OPPORTUNITY_UID      VARCHAR2(60),
    TIPO_PROCESO         VARCHAR2(100),
    ENTIDAD              VARCHAR2(200),
    TITULO               VARCHAR2(500),
    ESTADO_PORTAL        VARCHAR2(60),
    OFERTAS_PRESENTADAS  NUMBER DEFAULT 0,
    OFERTAS_CREADAS      NUMBER DEFAULT 0,
    FECHA_PUBLICACION    DATE,
    FECHA_LIMITE         DATE,
    FECHA_FIRMA_CONTRATO DATE,
    UNIDAD_REQUISICION   VARCHAR2(200),
    CODIGO_UNSPSC        VARCHAR2(50),
    LUGAR_ENTREGA        VARCHAR2(500),
    CREADO_EN            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ACTUALIZADO_EN       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_TLIC_OPORTUNIDAD_REF UNIQUE (NO_CIA, REFERENCIA)
);
/

CREATE SEQUENCE FAT.SEQ_TLIC_OPORTUNIDAD;
/

CREATE OR REPLACE TRIGGER FAT.TRG_TLIC_OPORTUNIDAD_ID
BEFORE INSERT ON FAT.TLIC_OPORTUNIDAD
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    :NEW.ID := FAT.SEQ_TLIC_OPORTUNIDAD.NEXTVAL;
END;
/

CREATE TABLE FAT.TLIC_DOCUMENTO (
    ID              NUMBER PRIMARY KEY,
    OPORTUNIDAD_ID  NUMBER NOT NULL,
    TIPO_DOCUMENTO  VARCHAR2(100),
    NOMBRE_ARCHIVO  VARCHAR2(300) NOT NULL,
    RUTA_ARCHIVO    VARCHAR2(500) NOT NULL,
    ESTADO          VARCHAR2(20) DEFAULT 'ok' NOT NULL,
    DESCARGADO_EN   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_TLIC_DOCUMENTO_OPP FOREIGN KEY (OPORTUNIDAD_ID) REFERENCES FAT.TLIC_OPORTUNIDAD(ID)
        ON DELETE CASCADE,
    CONSTRAINT CK_TLIC_DOCUMENTO_ESTADO CHECK (ESTADO IN ('ok', 'error'))
);
/

CREATE INDEX FAT.IX_TLIC_DOCUMENTO_OPP ON FAT.TLIC_DOCUMENTO (OPORTUNIDAD_ID);
/

CREATE SEQUENCE FAT.SEQ_TLIC_DOCUMENTO;
/

CREATE OR REPLACE TRIGGER FAT.TRG_TLIC_DOCUMENTO_ID
BEFORE INSERT ON FAT.TLIC_DOCUMENTO
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    :NEW.ID := FAT.SEQ_TLIC_DOCUMENTO.NEXTVAL;
END;
/

-- Agregado 2026-07-22 (Task 7, fix de code review): guarda el mensaje de error real de
-- un documento individual que falló al descargarse, en vez de sobrecargar RUTA_ARCHIVO
-- (que además es VARCHAR2(500) y podía truncar con ORA-12899). Mismo patrón que
-- TLIC_RUBRO_PDF.MENSAJE_ERROR. La tabla ya estaba viva y vacía al momento del cambio,
-- por eso es un ALTER TABLE aparte y no una reescritura del CREATE TABLE de arriba.
ALTER TABLE FAT.TLIC_DOCUMENTO ADD MENSAJE_ERROR VARCHAR2(1000);
/
