-- Fase: catalogo administrable de tipos de documento de empresa (Configuracion > Licitacion).
-- Ejecutar manualmente, mismo patron que 001_create_tlic.sql / 002_requisitos_empresa.sql.

CREATE TABLE FAT.TLIC_TIPO_DOCUMENTO (
    ID     NUMBER PRIMARY KEY,
    CODIGO VARCHAR2(30) NOT NULL,
    NOMBRE VARCHAR2(200) NOT NULL,
    ACTIVO VARCHAR2(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT UQ_TLIC_TIPO_DOCUMENTO_COD UNIQUE (CODIGO),
    CONSTRAINT CK_TLIC_TIPO_DOCUMENTO_ACTIVO CHECK (ACTIVO IN ('S', 'N'))
);
/

CREATE SEQUENCE FAT.SEQ_TLIC_TIPO_DOCUMENTO;
/

CREATE OR REPLACE TRIGGER FAT.TRG_TLIC_TIPO_DOCUMENTO_ID
BEFORE INSERT ON FAT.TLIC_TIPO_DOCUMENTO
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    :NEW.ID := FAT.SEQ_TLIC_TIPO_DOCUMENTO.NEXTVAL;
END;
/

INSERT INTO FAT.TLIC_TIPO_DOCUMENTO (CODIGO, NOMBRE) VALUES ('DGI', 'Constancia de Impuestos DGI al día');
INSERT INTO FAT.TLIC_TIPO_DOCUMENTO (CODIGO, NOMBRE) VALUES ('TSS', 'Constancia TSS al día');
INSERT INTO FAT.TLIC_TIPO_DOCUMENTO (CODIGO, NOMBRE) VALUES ('RNC', 'Documento RNC');
INSERT INTO FAT.TLIC_TIPO_DOCUMENTO (CODIGO, NOMBRE) VALUES ('ACTAS', 'Actas');
INSERT INTO FAT.TLIC_TIPO_DOCUMENTO (CODIGO, NOMBRE) VALUES ('REGMERC', 'Registro Mercantil');
COMMIT;
/

ALTER TABLE FAT.TLIC_DOCUMENTO_EMPRESA ADD TIPO_DOCUMENTO_ID NUMBER;
/

ALTER TABLE FAT.TLIC_DOCUMENTO_EMPRESA ADD CONSTRAINT FK_TLIC_DOCEMP_TIPODOC
    FOREIGN KEY (TIPO_DOCUMENTO_ID) REFERENCES FAT.TLIC_TIPO_DOCUMENTO(ID);
/
