from django.urls import path
from apps.legacy import acf_views
from apps.legacy.docs_print_data import (
    acf_acta_print_data,
    acf_comprobante_compra_print_data,
    acf_comprobante_retiro_print_data,
    acf_comprobante_cierre_print_data,
    acf_listado_activos_print_data,
    acf_listado_depreciacion_print_data,
    acf_rep_valuacion_print_data,
    acf_rep_por_grupo_print_data,
    acf_rep_por_departamento_print_data,
)

urlpatterns = [
    path('activos/<str:no_activo>/print-data/', acf_acta_print_data),
    path('comprobante-compra/<str:no_docu>/print-data/', acf_comprobante_compra_print_data),
    path('comprobante-retiro/<str:no_docu>/print-data/', acf_comprobante_retiro_print_data),
    path('comprobante-cierre/<str:ano_mes>/print-data/', acf_comprobante_cierre_print_data),
    path('rep-listado/print-data/', acf_listado_activos_print_data),
    path('rep-depreciacion/<str:ano_mes>/print-data/', acf_listado_depreciacion_print_data),
    path('rep-valuacion/print-data/', acf_rep_valuacion_print_data),
    path('rep-por-grupo/print-data/', acf_rep_por_grupo_print_data),
    path('rep-por-departamento/print-data/', acf_rep_por_departamento_print_data),
    path('cias/', acf_views.acf_cias),
    path('puntos/', acf_views.acf_puntos),
    path('categorias/', acf_views.acf_categorias),
    path('categorias/<str:categoria>/', acf_views.acf_categoria_detail),
    path('grupos/', acf_views.acf_grupos),
    path('grupos/<str:tipo>/<str:grupo>/', acf_views.acf_grupo_detail),
    path('subgrupos/', acf_views.acf_subgrupos),
    path('subgrupos/<str:tipo>/<str:grupo>/<str:subgrupo>/', acf_views.acf_subgrupo_detail),
    path('marcas/', acf_views.acf_marcas),
    path('marcas/<str:marca>/', acf_views.acf_marca_detail),
    path('responsables/', acf_views.acf_responsables),
    path('responsables/<str:responsable>/', acf_views.acf_responsable_detail),
    path('departamentos/', acf_views.acf_departamentos),
    path('departamentos/<str:departamento>/', acf_views.acf_departamento_detail),
    path('activos/', acf_views.acf_activos),
    path('activos/<str:no_cia>/<str:punto>/<str:no_activo>/', acf_views.acf_activo),
    path('rep-resumen/', acf_views.acf_rep_resumen),
    path('rep-por-grupo/', acf_views.acf_rep_por_grupo),
    path('rep-por-departamento/', acf_views.acf_rep_por_departamento),
    path('rep-valuacion/', acf_views.acf_rep_valuacion),
    path('compra/', acf_views.acf_compra),
    path('retiro/', acf_views.acf_retiro),
    path('depreciacion/preview/', acf_views.acf_depreciacion_preview),
    path('depreciacion/', acf_views.acf_depreciacion),
    path('cierre/status/', acf_views.acf_cierre_status),
    path('cierres/', acf_views.acf_cierres),
    path('cierre/', acf_views.acf_aplicar_cierre),
]
