-- ZentoryERP MCP — tablas de auth y auditoría
-- Aplicar como JCABREU contra Oracle AB:
--   sqlplus JCABREU/<pass>@AB @0001_initial.sql
-- (Django default DB = SQLite; tablas Oracle se gestionan vía apps.legacy.client,
--  no via Django migrations.)

CREATE TABLE ABREGONZA.TMCP_TOKEN (
    TOKEN_ID         VARCHAR2(36) NOT NULL,
    USUARIO          VARCHAR2(30) NOT NULL,
    NO_CIA           VARCHAR2(2),
    BLOQUEAR_CIA     CHAR(1)      DEFAULT 'N' NOT NULL,
    PUNTO            VARCHAR2(2),
    BLOQUEAR_PUNTO   CHAR(1)      DEFAULT 'N' NOT NULL,
    NOMBRE           VARCHAR2(100) NOT NULL,
    TOKEN_HASH       VARCHAR2(128) NOT NULL,
    PREFIJO          VARCHAR2(8)   NOT NULL,
    FECHA_CREACION   DATE          DEFAULT SYSDATE NOT NULL,
    FECHA_EXPIRA     DATE,
    FECHA_ULTIMO_USO DATE,
    IP_ULTIMO_USO    VARCHAR2(45),
    ST_ACTIVO        CHAR(1)       DEFAULT 'S' NOT NULL,
    CREADO_POR       VARCHAR2(30)  NOT NULL,
    CONSTRAINT PK_TMCP_TOKEN PRIMARY KEY (TOKEN_ID),
    CONSTRAINT UQ_TMCP_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT CK_TMCP_TOKEN_BLOQUEAR_CIA   CHECK (BLOQUEAR_CIA   IN ('S','N')),
    CONSTRAINT CK_TMCP_TOKEN_BLOQUEAR_PUNTO CHECK (BLOQUEAR_PUNTO IN ('S','N')),
    CONSTRAINT CK_TMCP_TOKEN_ST_ACTIVO      CHECK (ST_ACTIVO      IN ('S','N'))
);

CREATE INDEX ABREGONZA.IX_TMCP_TOKEN_USUARIO ON ABREGONZA.TMCP_TOKEN (USUARIO);
CREATE INDEX ABREGONZA.IX_TMCP_TOKEN_ACTIVO  ON ABREGONZA.TMCP_TOKEN (ST_ACTIVO, FECHA_EXPIRA);

CREATE TABLE ABREGONZA.TMCP_TOKEN_USO (
    USO_ID         NUMBER(15) NOT NULL,
    TOKEN_ID       VARCHAR2(36) NOT NULL,
    FECHA          DATE         DEFAULT SYSDATE NOT NULL,
    TOOL           VARCHAR2(80) NOT NULL,
    PARAMS_HASH    VARCHAR2(64),
    IP             VARCHAR2(45),
    OK             CHAR(1)      DEFAULT 'S' NOT NULL,
    ERROR_CODE     VARCHAR2(40),
    DURATION_MS    NUMBER(10),
    CONSTRAINT PK_TMCP_TOKEN_USO PRIMARY KEY (USO_ID),
    CONSTRAINT CK_TMCP_TOKEN_USO_OK CHECK (OK IN ('S','N'))
);

CREATE SEQUENCE ABREGONZA.SQ_TMCP_TOKEN_USO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX ABREGONZA.IX_TMCP_TOKEN_USO_FECHA       ON ABREGONZA.TMCP_TOKEN_USO (FECHA DESC);
CREATE INDEX ABREGONZA.IX_TMCP_TOKEN_USO_TOKEN_FECHA ON ABREGONZA.TMCP_TOKEN_USO (TOKEN_ID, FECHA DESC);
CREATE INDEX ABREGONZA.IX_TMCP_TOKEN_USO_TOOL_FECHA  ON ABREGONZA.TMCP_TOKEN_USO (TOOL, FECHA DESC);

EXIT;
