-- ============================================================================
-- TREP_* : reportes de problemas ("Soporte") de ZentoryERP
-- Owner: ABREGONZA
-- Spec : backend/docs/superpowers/specs/2026-07-22-reportes-soporte-design.md
-- NO se ejecuta automaticamente. Correr manualmente:
--   sqlplus JCABREU/508192003@AB @backend/apps/reportes/sql/001_create_trep.sql
-- ============================================================================

CREATE TABLE ABREGONZA.TREP_PROBLEMA (
    REPORTE_ID           VARCHAR2(36)  NOT NULL,
    USUARIO              VARCHAR2(30)  NOT NULL,
    MODULO               VARCHAR2(20)  NOT NULL,
    TITULO               VARCHAR2(200) NOT NULL,
    DESCRIPCION          CLOB,
    ESTADO               VARCHAR2(15)  DEFAULT 'ABIERTO' NOT NULL,
    NOTA_RESOLUCION      CLOB,
    RESUELTO_POR         VARCHAR2(30),
    FECHA_CREACION       DATE DEFAULT SYSDATE NOT NULL,
    FECHA_ACTUALIZACION  DATE DEFAULT SYSDATE NOT NULL,
    FECHA_RESOLUCION     DATE,
    CONSTRAINT PK_TREP_PROBLEMA PRIMARY KEY (REPORTE_ID),
    CONSTRAINT CK_TREP_PROB_ESTADO CHECK (
        ESTADO IN ('ABIERTO','EN_PROGRESO','COMPLETADO','CANCELADO')
    )
);

CREATE INDEX IX_TREP_PROB_ESTADO ON ABREGONZA.TREP_PROBLEMA (ESTADO, FECHA_CREACION);
CREATE INDEX IX_TREP_PROB_USR    ON ABREGONZA.TREP_PROBLEMA (USUARIO, FECHA_CREACION DESC);

CREATE TABLE ABREGONZA.TREP_IMAGEN (
    IMAGEN_ID       VARCHAR2(36)  NOT NULL,
    REPORTE_ID      VARCHAR2(36)  NOT NULL,
    NOMBRE_ARCHIVO  VARCHAR2(200),
    MEDIA_TYPE      VARCHAR2(50)  NOT NULL,
    CONTENIDO       BLOB          NOT NULL,
    TAMANO_BYTES    NUMBER(10)    NOT NULL,
    FECHA_CREACION  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TREP_IMAGEN PRIMARY KEY (IMAGEN_ID),
    CONSTRAINT FK_TREP_IMG_REPORTE
        FOREIGN KEY (REPORTE_ID) REFERENCES ABREGONZA.TREP_PROBLEMA(REPORTE_ID)
        ON DELETE CASCADE
);

CREATE INDEX IX_TREP_IMG_REPORTE ON ABREGONZA.TREP_IMAGEN (REPORTE_ID);

GRANT SELECT, INSERT, UPDATE, DELETE ON ABREGONZA.TREP_PROBLEMA TO JCABREU;
GRANT SELECT, INSERT, UPDATE, DELETE ON ABREGONZA.TREP_IMAGEN   TO JCABREU;

CREATE OR REPLACE SYNONYM JCABREU.TREP_PROBLEMA FOR ABREGONZA.TREP_PROBLEMA;
CREATE OR REPLACE SYNONYM JCABREU.TREP_IMAGEN   FOR ABREGONZA.TREP_IMAGEN;

COMMIT;
EXIT;
