# Generated by Django 5.1.13 on 2026-07-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], max_length=10)),
                ('no_cia', models.CharField(blank=True, max_length=2, null=True)),
                ('estado', models.CharField(choices=[('corriendo', 'corriendo'), ('completado', 'completado'), ('completado_con_errores', 'completado_con_errores'), ('error', 'error')], default='corriendo', max_length=30)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('resumen', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-iniciado_en'],
            },
        ),
    ]
