# Generated by Django 5.1.13 on 2026-07-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oportunidad_id', models.IntegerField()),
                ('estado', models.CharField(choices=[('corriendo', 'Corriendo'), ('listo_para_enviar', 'Listo para enviar'), ('faltan_documentos', 'Faltan documentos'), ('error', 'Error'), ('enviado', 'Enviado')], default='corriendo', max_length=20)),
                ('resumen', models.JSONField(default=dict)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
