from django.urls import path
from .views import (
    FatNCFListView, FatNCFAlertsView, FatSearchView, FatDocumentTypesView,
    FatFacturasView, FatFacturaDetailView, FatAnularFacturaView,
    FatVendedoresView, FatClientesView, FatCondicionesPagoView,
    FatCompaniasView, FatPuntosView, FatTiposPagoView, FatListasPrecioView,
    FatProductosView, FatProductoEmpaquesView, FatTransportistasView, FatNotasView,
    FatConducesView, FatConduceDetailView, FatCuadreCajaView,
    FatRepVentasView, FatRep607View, FatRepNcfNulosView, FatRepFacturasRncView,
    FatRepMargenBrutoView,
    FatRepVentasVendedorView, FatRepVentasClienteView, FatRepAnaliticaView,
    FatCierresView, FatGenerarAsientosView, FatProximoNcfView, FatNcfUsadoView,
    FatProximoNoFacturaView, DashboardVentasMesView,
)
from .views_print import (
    fat_documento_pdf, fat_documento_pos_pdf, fat_lista_facturas_pdf,
    fat_conduce_pdf, fat_lista_conduces_pdf,
    fat_lista_precio_pdf, fat_rep_607_pdf,
    fat_rep_ncf_nulos_pdf, fat_rep_facturas_rnc_pdf, fat_rep_margen_bruto_pdf,
    fat_cuadre_caja_pdf, fat_rep_ventas_productos_pdf,
)

urlpatterns = [
    path('fat/ncf/', FatNCFListView.as_view()),
    path('fat/ncf/alerts/', FatNCFAlertsView.as_view()),
    path('fat/documents/', FatDocumentTypesView.as_view()),
    path('fat/search/', FatSearchView.as_view()),
    path('fat/facturas/', FatFacturasView.as_view()),
    path('fat/facturas/anular/', FatAnularFacturaView.as_view()),
    path('fat/facturas/<str:tipo>/<str:no_factura>/', FatFacturaDetailView.as_view()),
    path('fat/vendedores/', FatVendedoresView.as_view()),
    path('fat/clientes/', FatClientesView.as_view()),
    path('fat/condiciones-pago/', FatCondicionesPagoView.as_view()),
    path('fat/companias/', FatCompaniasView.as_view()),
    path('fat/puntos/', FatPuntosView.as_view()),
    path('fat/tipos-pago/', FatTiposPagoView.as_view()),
    path('fat/listas-precio/', FatListasPrecioView.as_view()),
    path('fat/productos/', FatProductosView.as_view()),
    path('fat/producto-empaques/', FatProductoEmpaquesView.as_view()),
    path('fat/transportistas/', FatTransportistasView.as_view()),
    path('fat/notas/', FatNotasView.as_view()),
    path('fat/conduces/', FatConducesView.as_view()),
    path('fat/conduces/<str:tipo>/<str:no_conduce>/', FatConduceDetailView.as_view()),
    path('fat/cuadre-caja/', FatCuadreCajaView.as_view()),
    path('fat/rep-ventas/', FatRepVentasView.as_view()),
    path('fat/rep-607/', FatRep607View.as_view()),
    path('fat/rep-ncf-nulos/', FatRepNcfNulosView.as_view()),
    path('fat/rep-facturas-rnc/', FatRepFacturasRncView.as_view()),
    path('fat/rep-margen-bruto/', FatRepMargenBrutoView.as_view()),
    path('fat/rep-ventas-vendedor/', FatRepVentasVendedorView.as_view()),
    path('fat/rep-ventas-cliente/', FatRepVentasClienteView.as_view()),
    path('fat/rep-analitica/', FatRepAnaliticaView.as_view()),
    path('fat/cierres/', FatCierresView.as_view()),
    path('fat/generar-asientos/', FatGenerarAsientosView.as_view()),
    path('fat/proximo-ncf/', FatProximoNcfView.as_view()),
    path('fat/ncf-usado/', FatNcfUsadoView.as_view()),
    path('fat/proximo-no-factura/', FatProximoNoFacturaView.as_view()),
    path('fat/documentos/<str:tipo>/<str:no_factura>/pdf/', fat_documento_pdf),
    path('fat/documentos/<str:tipo>/<str:no_factura>/pos-pdf/', fat_documento_pos_pdf),
    path('fat/reportes/listado/pdf/', fat_lista_facturas_pdf),
    path('fat/conduces/<str:tipo>/<str:no_conduce>/pdf/', fat_conduce_pdf),
    path('fat/reportes/listado-conduces/pdf/', fat_lista_conduces_pdf),
    path('fat/reportes/lista-precio/pdf/', fat_lista_precio_pdf),
    path('fat/reportes/607/pdf/', fat_rep_607_pdf),
    path('fat/reportes/ncf-nulos/pdf/', fat_rep_ncf_nulos_pdf),
    path('fat/reportes/facturas-rnc/pdf/', fat_rep_facturas_rnc_pdf),
    path('fat/reportes/margen-bruto/pdf/', fat_rep_margen_bruto_pdf),
    path('fat/reportes/cuadre-caja/pdf/', fat_cuadre_caja_pdf),
    path('fat/reportes/ventas-productos/pdf/', fat_rep_ventas_productos_pdf),
    path('dashboard/ventas-mes/', DashboardVentasMesView.as_view()),
]
