from django.urls import path
from .views import (
    FatNCFListView, FatNCFAlertsView, FatSearchView, FatDocumentTypesView,
    FatFacturasView, FatFacturaDetailView, FatAnularFacturaView,
    FatVendedoresView, FatClientesView, FatCondicionesPagoView,
    FatCompaniasView, FatPuntosView, FatTiposPagoView, FatListasPrecioView,
    FatProductosView, FatProductoEmpaquesView, FatTransportistasView, FatNotasView,
    FatConducesView, FatCuadreCajaView,
    FatRepVentasView, FatRep607View, FatRepNcfNulosView,
    FatRepVentasVendedorView, FatRepVentasClienteView, FatRepAnaliticaView,
    FatCierresView, FatGenerarAsientosView,
)
from .views_print import fat_documento_pdf

urlpatterns = [
    path('fat/ncf/', FatNCFListView.as_view()),
    path('fat/ncf/alerts/', FatNCFAlertsView.as_view()),
    path('fat/documents/', FatDocumentTypesView.as_view()),
    path('fat/search/', FatSearchView.as_view()),
    path('fat/facturas/', FatFacturasView.as_view()),
    path('fat/facturas/anular/', FatAnularFacturaView.as_view()),
    path('fat/facturas/<str:tipo>/<str:no_factura>/', FatFacturaDetailView.as_view()),
    path('fat/vendedores/', FatVendedoresView.as_view()),
    path('fat/clientes/', FatClientesView.as_view()),
    path('fat/condiciones-pago/', FatCondicionesPagoView.as_view()),
    path('fat/companias/', FatCompaniasView.as_view()),
    path('fat/puntos/', FatPuntosView.as_view()),
    path('fat/tipos-pago/', FatTiposPagoView.as_view()),
    path('fat/listas-precio/', FatListasPrecioView.as_view()),
    path('fat/productos/', FatProductosView.as_view()),
    path('fat/producto-empaques/', FatProductoEmpaquesView.as_view()),
    path('fat/transportistas/', FatTransportistasView.as_view()),
    path('fat/notas/', FatNotasView.as_view()),
    path('fat/conduces/', FatConducesView.as_view()),
    path('fat/cuadre-caja/', FatCuadreCajaView.as_view()),
    path('fat/rep-ventas/', FatRepVentasView.as_view()),
    path('fat/rep-607/', FatRep607View.as_view()),
    path('fat/rep-ncf-nulos/', FatRepNcfNulosView.as_view()),
    path('fat/rep-ventas-vendedor/', FatRepVentasVendedorView.as_view()),
    path('fat/rep-ventas-cliente/', FatRepVentasClienteView.as_view()),
    path('fat/rep-analitica/', FatRepAnaliticaView.as_view()),
    path('fat/cierres/', FatCierresView.as_view()),
    path('fat/generar-asientos/', FatGenerarAsientosView.as_view()),
    path('fat/documentos/<str:tipo>/<str:no_factura>/pdf/', fat_documento_pdf),
]
